version: '3.8'
services:
  postgres:
    image: postgres:15.3-alpine
    environment:
      POSTGRES_USER: informator
      POSTGRES_DB: axum_db
      POSTGRES_PASSWORD: password
    volumes:
      - ./database/postgres/docker-entrypoint-initdb:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
